# Generated by Django 5.1.5 on 2025-01-16 12:55

import spotify.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_url", models.URLField(max_length=500)),
                ("followers_total", models.IntegerField(default=0)),
                ("genres", models.JSONField(default=spotify.models.default_genres)),
                ("api_href", models.CharField(default="no api_href", max_length=500)),
                ("spotify_id", models.CharField(default="Unknown Id", max_length=50)),
                ("name", models.CharField(default="Unknown Artist", max_length=200)),
                ("popularity", models.IntegerField(default=0)),
                ("uri", models.CharField(default="Unknown Uri", max_length=100)),
                ("images", models.ManyToManyField(to="spotify.image")),
            ],
        ),
    ]
